import PageHeader from "@/components/PageHeader";
import { employees, projects, invoices, clients } from "@/data/mockData";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
} from "recharts";
import { useSalaryStats } from "@/hooks/useSalary";

const formatCurrency = (value: number) => {
  if (value >= 100000) return `₹${(value / 100000).toFixed(1)}L`;
  if (value >= 1000) return `₹${(value / 1000).toFixed(0)}K`;
  return `₹${value}`;
};

const Reports = () => {
  // Revenue per employee
  const revenueData = [...employees]
    .sort((a, b) => b.revenueGenerated - a.revenueGenerated)
    .map((e) => ({
      name: e.name.split(" ")[0],
      revenue: e.revenueGenerated,
    }));

  // Project status breakdown
  const statusCounts = projects.reduce((acc, p) => {
    acc[p.status] = (acc[p.status] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  const projectStatusData = Object.entries(statusCounts).map(([status, count]) => ({
    name: status.replace("-", " ").replace(/\b\w/g, (l) => l.toUpperCase()),
    value: count,
  }));

  const pieColors = [
    "hsl(173, 80%, 36%)",
    "hsl(38, 92%, 50%)",
    "hsl(210, 92%, 55%)",
    "hsl(152, 69%, 40%)",
    "hsl(0, 72%, 51%)",
  ];

  // Department breakdown
  const deptData = employees.reduce((acc, e) => {
    const existing = acc.find((d) => d.department === e.department);
    if (existing) {
      existing.count += 1;
      existing.revenue += e.revenueGenerated;
    } else {
      acc.push({ department: e.department, count: 1, revenue: e.revenueGenerated });
    }
    return acc;
  }, [] as { department: string; count: number; revenue: number }[]);

  // Invoice status
  const invoiceStatusCounts = invoices.reduce((acc, inv) => {
    acc[inv.status] = (acc[inv.status] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  const { data: salaryStats = [] } = useSalaryStats();

  // Combine monthly data for chart
  const salaryChartData = salaryStats.reduce((acc: any[], stat) => {
    const label = `${stat._id.month} ${stat._id.year}`;
    const existing = acc.find(d => d.name === label);
    const amountKey = stat._id.payeeModel === 'employee' ? 'Employee' : 'Intern';

    if (existing) {
      existing[amountKey] = (existing[amountKey] || 0) + stat.totalAmount;
      existing.total = (existing.total || 0) + stat.totalAmount;
    } else {
      acc.push({
        name: label,
        [amountKey]: stat.totalAmount,
        total: stat.totalAmount,
        rawMonth: stat._id.month,
        rawYear: stat._id.year
      });
    }
    return acc;
  }, []).sort((a, b) => (a.rawYear !== b.rawYear ? a.rawYear - b.rawYear : months.indexOf(a.rawMonth) - months.indexOf(b.rawMonth)));

  const months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

  return (
    <div>
      <PageHeader title="Reports" subtitle="Business intelligence & analytics" />

      <div className="p-6 space-y-6">
        {/* Row 1 */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Revenue per Employee */}
          <div className="bg-card rounded-xl border border-border p-5">
            <h3 className="text-sm font-semibold text-foreground mb-1">Revenue per Employee</h3>
            <p className="text-xs text-muted-foreground mb-4">Total revenue generated by each team member</p>
            <div className="h-[280px]">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={revenueData} layout="vertical">
                  <CartesianGrid strokeDasharray="3 3" stroke="hsl(214, 20%, 90%)" />
                  <XAxis type="number" tickFormatter={formatCurrency} tick={{ fontSize: 11 }} stroke="hsl(215, 14%, 50%)" />
                  <YAxis type="category" dataKey="name" tick={{ fontSize: 11 }} stroke="hsl(215, 14%, 50%)" width={60} />
                  <Tooltip formatter={(value: number) => formatCurrency(value)} />
                  <Bar dataKey="revenue" name="Revenue" fill="hsl(173, 80%, 36%)" radius={[0, 6, 6, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Project Status */}
          <div className="bg-card rounded-xl border border-border p-5">
            <h3 className="text-sm font-semibold text-foreground mb-1">Project Status Distribution</h3>
            <p className="text-xs text-muted-foreground mb-4">Current status of all projects</p>
            <div className="h-[220px]">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie data={projectStatusData} cx="50%" cy="50%" outerRadius={90} dataKey="value" label={({ name, value }) => `${name}: ${value}`}>
                    {projectStatusData.map((_, index) => (
                      <Cell key={index} fill={pieColors[index % pieColors.length]} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </div>
        </div>

        {/* Row 2: Summary Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">
          <div className="stat-card">
            <p className="text-[10px] text-muted-foreground uppercase tracking-wider">Total Clients</p>
            <p className="text-2xl font-bold text-foreground mt-1">{clients.length}</p>
            <p className="text-xs text-success mt-1">{clients.filter(c => c.status === "active").length} active</p>
          </div>
          <div className="stat-card">
            <p className="text-[10px] text-muted-foreground uppercase tracking-wider">Total Projects</p>
            <p className="text-2xl font-bold text-foreground mt-1">{projects.length}</p>
            <p className="text-xs text-muted-foreground mt-1">{projects.filter(p => p.status === "completed").length} completed</p>
          </div>
          <div className="stat-card">
            <p className="text-[10px] text-muted-foreground uppercase tracking-wider">Invoices Paid</p>
            <p className="text-2xl font-bold text-foreground mt-1">{invoiceStatusCounts["paid"] || 0}/{invoices.length}</p>
            <p className="text-xs text-warning mt-1">{invoiceStatusCounts["pending"] || 0} pending</p>
          </div>
          <div className="stat-card">
            <p className="text-[10px] text-muted-foreground uppercase tracking-wider">Team Size</p>
            <p className="text-2xl font-bold text-foreground mt-1">{employees.length}</p>
            <p className="text-xs text-muted-foreground mt-1">{deptData.length} departments</p>
          </div>
        </div>

        {/* Department Breakdown */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="bg-card rounded-xl border border-border p-5">
            <h3 className="text-sm font-semibold text-foreground mb-1">Department Overview</h3>
            <p className="text-xs text-muted-foreground mb-4">Team size and revenue by department</p>
            <div className="h-[250px]">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={deptData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="hsl(214, 20%, 90%)" />
                  <XAxis dataKey="department" tick={{ fontSize: 11 }} stroke="hsl(215, 14%, 50%)" />
                  <YAxis yAxisId="left" tick={{ fontSize: 11 }} stroke="hsl(215, 14%, 50%)" />
                  <YAxis yAxisId="right" orientation="right" tickFormatter={formatCurrency} tick={{ fontSize: 11 }} stroke="hsl(215, 14%, 50%)" />
                  <Tooltip formatter={(value: number, name: string) => name === "Revenue" ? formatCurrency(value) : value} />
                  <Bar yAxisId="left" dataKey="count" name="Team Size" fill="hsl(220, 70%, 50%)" radius={[4, 4, 0, 0]} />
                  <Bar yAxisId="right" dataKey="revenue" name="Revenue" fill="hsl(173, 80%, 36%)" radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

          <div className="bg-card rounded-xl border border-border p-5">
            <h3 className="text-sm font-semibold text-foreground mb-1">Salary Expenditure</h3>
            <p className="text-xs text-muted-foreground mb-4">Total payments made over time</p>
            <div className="h-[250px]">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={salaryChartData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="hsl(214, 20%, 90%)" />
                  <XAxis dataKey="name" tick={{ fontSize: 11 }} stroke="hsl(215, 14%, 50%)" />
                  <YAxis tickFormatter={formatCurrency} tick={{ fontSize: 11 }} stroke="hsl(215, 14%, 50%)" />
                  <Tooltip formatter={(value: number) => formatCurrency(value)} />
                  <Bar dataKey="Employee" stackId="a" fill="hsl(210, 92%, 55%)" radius={[4, 4, 0, 0]} />
                  <Bar dataKey="Intern" stackId="a" fill="hsl(173, 80%, 36%)" radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Reports;
